---
- name: Create Cloud router
  hosts: host_1
  become: true
  gather_facts: false

  vars_files:
    - group_vars/group/all/vault.yml

  vars:
    router_name: cloud_router
    router_hostname: cloud-router
    router_instance_id: cloud-router-001

    router_image: "/mnt/a400/ISO/alpine-3.24.2-x86_64-cloudinit-r0.qcow2"
    router_directory: "/mnt/p5+/KVM/cloud_router"
    router_disk: "/mnt/p5+/KVM/cloud_router/cloud_router.qcow2"

    router_lan_address: 192.168.74.1
    router_lan_subnet: 192.168.74.0/27
    router_wan_mac: "52:54:00:74:01:01"
    router_lan_mac: "52:54:00:74:01:02"

  roles:
    - router_creation


- name: Create East router
  hosts: host_1
  become: true
  gather_facts: false

  vars_files:
    - group_vars/group/all/vault.yml

  vars:
    router_name: east_router
    router_hostname: east-router
    router_instance_id: east-router-001

    router_image: "/mnt/a400/ISO/alpine-3.24.2-x86_64-cloudinit-r0.qcow2"
    router_directory: "/mnt/p5+/KVM/east_router"
    router_disk: "/mnt/p5+/KVM/east_router/east_router.qcow2"

    router_lan_address: 192.168.72.1
    router_lan_subnet: 192.168.72.0/27
    router_wan_mac: "52:54:00:72:01:01"
    router_lan_mac: "52:54:00:72:01:02"

  roles:
    - router_creation


- name: Create West router
  hosts: host_2
  become: true
  gather_facts: false

  vars_files:
    - group_vars/group/all/vault.yml

  vars:

    create_west: true

    router_name: west_router
    router_hostname: west-router
    router_instance_id: west-router-001

    # Пути пока неизвестны.
    router_image: "/mnt/disk/ISO/alpine-3.24.2-x86_64-cloudinit-r0.qcow2"
    router_directory: "/mnt/disk/VM/west_router"
    router_disk: "/mnt/disk/VM/west_router/west_router.qcow2"

    router_lan_address: 192.168.73.1
    router_lan_subnet: 192.168.73.0/27
    router_wan_mac: "52:54:00:73:01:01"
    router_lan_mac: "52:54:00:73:01:02"

  roles:
    - role: router_creation
      when: create_west | bool
