---
- name: Create administrator accounts
  hosts: linux_servers
  become: true
  gather_facts: true

  vars_files:
    - group_vars/group/all/vault.yml

  tasks:
    - name: Create users with sudo access
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password_hash }}"
        update_password: always
        shell: "{{ '/bin/ash' if ansible_facts.distribution == 'Alpine' else '/bin/bash' }}"
        groups: "{{ ['wheel'] if ansible_facts.distribution == 'Alpine' else ['sudo'] }}"
        append: true
        create_home: true
        state: present
      loop: "{{ vault_admin_users }}"
      no_log: true
