---
# Disk size: 2 GiB
router_disk_size_bytes: 2147483648

# VM resources
router_memory_mb: 1024
router_vcpus: 1

# Libvirt networks
router_wan_network: default
router_lan_network: internal

# LAN subnet mask: /27
router_lan_netmask: 255.255.255.224

# Public SSH key on the Ansible control node
router_public_key_file: ~/.ssh/ansible.pub
